FROM node:20-alpine AS base

RUN apk add --no-cache git openssh-client && \
    git config --global url."https://github.com/".insteadOf "git@github.com:" && \
    git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

WORKDIR /app

COPY package.json package-lock.json turbo.json ./
COPY apps/ ./apps/

RUN npm cache clean --force && npm install --legacy-peer-deps

RUN npm run build --filter=@dtc/backend...

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=base /app ./

EXPOSE 9000

CMD ["npm", "run", "start", "--filter=@dtc/backend"]
