FROM postgres:16

ENV POSTGRES_DB=strawb-db
ENV POSTGRES_USER=strawb-user
ENV POSTGRES_PASSWORD=yourpassword
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/16/bin
ENV GOSU_VERSION=1.19
ENV LANG=en_US.utf8
ENV PG_MAJOR=16
ENV PG_VERSION=16.14-1.pgdg13+1
ENV PGDATA=/var/lib/postgresql/data

EXPOSE 5432
