FROM node:20-alpine AS base

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/backend/package.json ./apps/backend/
COPY apps/storefront/package.json ./apps/storefront/

RUN npm ci

COPY . .

RUN npm run build --filter=@dtc/backend...

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=base /app ./

EXPOSE 9000

CMD ["npm", "run", "start", "--filter=@dtc/backend"]
