FROM node:20-alpine AS base

RUN apk add --no-cache git openssh-client

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/ ./apps/

RUN npm install --legacy-peer-deps

RUN npm run build --filter=@dtc/storefront...

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=base /app ./

EXPOSE 8000

CMD ["npm", "run", "start", "--filter=@dtc/storefront"]
