services:
  postgres:
    image: postgres:16-alpine
    container_name: strawb_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strawb-db
      POSTGRES_USER: strawb-user
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "127.0.0.1:5433:5432"  # Localhost par 5433 port expose ho gaya, public nahi!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy

volumes:
  postgres_data:

networks:
  proxy:
    external: true